### ISSUE TITLE
Risa Odin staking testnet, tier settings 

### ISSUE THREAD

**Issue by HPAr007** [risasoft/staking#2]
Hi. I have been testing Risa staking on Odin platform. The staking, reinvesting and claim process is seamless however my Tier has not yet upgraded and still stuck at Bronze. Could you check it? Thanks
My ERD address : erd1sv0e9udz3acxulek4jcs3p3hq3jpsc3nh6tqus7l00x846wp9fwq4rm4jf

**Comment by risasoft** [comment]
Thanks for testing! If you stake more, the tier may drop and the timer resets.

Sent you a thank you for testing 👍
