### ISSUE TITLE
Issue with stacking on Odin App

### ISSUE THREAD

**Issue by CedricCi** [risasoft/staking#3]
Hello !
I tried to follow the instructions in your Telegram message of May 4th (*** Get Ready for $RISA Staking ***) by using faucet to obtain xEGLD and xRISA, it worked perfectly.

However, it says to go to "Stake your xRISA tokens at: https://odin-dapp-development.netlify.app/staking", but when I connect my wallet here, it does not see my xRISA tokens just obtained.

I may have done something wrong ...

Thank you in advance.

erd1j3jqj09wmq862y3fvz2qdu00lngghpwhlz6kmt6dh539gwqqpceqnwqqvv

**Comment by risasoft** [comment]
Hi this is for testnet testing. The test period is over.

To stake on production app go to
https://odindefi.app/staking

**Comment by risasoft** [comment]
Closing as stake is now managed on risastaking.com
